// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/opctl/opctl/sdks/go/model"
	"github.com/opctl/opctl/sdks/go/node"
)

type FakeNode struct {
	GetDataStub        func(context.Context, chan model.Event, string, model.GetDataReq) (model.ReadSeekCloser, error)
	getDataMutex       sync.RWMutex
	getDataArgsForCall []struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 model.GetDataReq
	}
	getDataReturns struct {
		result1 model.ReadSeekCloser
		result2 error
	}
	getDataReturnsOnCall map[int]struct {
		result1 model.ReadSeekCloser
		result2 error
	}
	LabelStub        func() string
	labelMutex       sync.RWMutex
	labelArgsForCall []struct {
	}
	labelReturns struct {
		result1 string
	}
	labelReturnsOnCall map[int]struct {
		result1 string
	}
	ListDescendantsStub        func(context.Context, chan model.Event, string, model.ListDescendantsReq) ([]*model.DirEntry, error)
	listDescendantsMutex       sync.RWMutex
	listDescendantsArgsForCall []struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 model.ListDescendantsReq
	}
	listDescendantsReturns struct {
		result1 []*model.DirEntry
		result2 error
	}
	listDescendantsReturnsOnCall map[int]struct {
		result1 []*model.DirEntry
		result2 error
	}
	StartOpStub        func(context.Context, chan model.Event, model.StartOpReq) (map[string]*model.Value, error)
	startOpMutex       sync.RWMutex
	startOpArgsForCall []struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 model.StartOpReq
	}
	startOpReturns struct {
		result1 map[string]*model.Value
		result2 error
	}
	startOpReturnsOnCall map[int]struct {
		result1 map[string]*model.Value
		result2 error
	}
	TryResolveStub        func(context.Context, chan model.Event, string, string) (model.DataHandle, error)
	tryResolveMutex       sync.RWMutex
	tryResolveArgsForCall []struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 string
	}
	tryResolveReturns struct {
		result1 model.DataHandle
		result2 error
	}
	tryResolveReturnsOnCall map[int]struct {
		result1 model.DataHandle
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeNode) GetData(arg1 context.Context, arg2 chan model.Event, arg3 string, arg4 model.GetDataReq) (model.ReadSeekCloser, error) {
	fake.getDataMutex.Lock()
	ret, specificReturn := fake.getDataReturnsOnCall[len(fake.getDataArgsForCall)]
	fake.getDataArgsForCall = append(fake.getDataArgsForCall, struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 model.GetDataReq
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("GetData", []interface{}{arg1, arg2, arg3, arg4})
	fake.getDataMutex.Unlock()
	if fake.GetDataStub != nil {
		return fake.GetDataStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getDataReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) GetDataCallCount() int {
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	return len(fake.getDataArgsForCall)
}

func (fake *FakeNode) GetDataCalls(stub func(context.Context, chan model.Event, string, model.GetDataReq) (model.ReadSeekCloser, error)) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = stub
}

func (fake *FakeNode) GetDataArgsForCall(i int) (context.Context, chan model.Event, string, model.GetDataReq) {
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	argsForCall := fake.getDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeNode) GetDataReturns(result1 model.ReadSeekCloser, result2 error) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = nil
	fake.getDataReturns = struct {
		result1 model.ReadSeekCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) GetDataReturnsOnCall(i int, result1 model.ReadSeekCloser, result2 error) {
	fake.getDataMutex.Lock()
	defer fake.getDataMutex.Unlock()
	fake.GetDataStub = nil
	if fake.getDataReturnsOnCall == nil {
		fake.getDataReturnsOnCall = make(map[int]struct {
			result1 model.ReadSeekCloser
			result2 error
		})
	}
	fake.getDataReturnsOnCall[i] = struct {
		result1 model.ReadSeekCloser
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) Label() string {
	fake.labelMutex.Lock()
	ret, specificReturn := fake.labelReturnsOnCall[len(fake.labelArgsForCall)]
	fake.labelArgsForCall = append(fake.labelArgsForCall, struct {
	}{})
	fake.recordInvocation("Label", []interface{}{})
	fake.labelMutex.Unlock()
	if fake.LabelStub != nil {
		return fake.LabelStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.labelReturns
	return fakeReturns.result1
}

func (fake *FakeNode) LabelCallCount() int {
	fake.labelMutex.RLock()
	defer fake.labelMutex.RUnlock()
	return len(fake.labelArgsForCall)
}

func (fake *FakeNode) LabelCalls(stub func() string) {
	fake.labelMutex.Lock()
	defer fake.labelMutex.Unlock()
	fake.LabelStub = stub
}

func (fake *FakeNode) LabelReturns(result1 string) {
	fake.labelMutex.Lock()
	defer fake.labelMutex.Unlock()
	fake.LabelStub = nil
	fake.labelReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeNode) LabelReturnsOnCall(i int, result1 string) {
	fake.labelMutex.Lock()
	defer fake.labelMutex.Unlock()
	fake.LabelStub = nil
	if fake.labelReturnsOnCall == nil {
		fake.labelReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.labelReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeNode) ListDescendants(arg1 context.Context, arg2 chan model.Event, arg3 string, arg4 model.ListDescendantsReq) ([]*model.DirEntry, error) {
	fake.listDescendantsMutex.Lock()
	ret, specificReturn := fake.listDescendantsReturnsOnCall[len(fake.listDescendantsArgsForCall)]
	fake.listDescendantsArgsForCall = append(fake.listDescendantsArgsForCall, struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 model.ListDescendantsReq
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("ListDescendants", []interface{}{arg1, arg2, arg3, arg4})
	fake.listDescendantsMutex.Unlock()
	if fake.ListDescendantsStub != nil {
		return fake.ListDescendantsStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listDescendantsReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) ListDescendantsCallCount() int {
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	return len(fake.listDescendantsArgsForCall)
}

func (fake *FakeNode) ListDescendantsCalls(stub func(context.Context, chan model.Event, string, model.ListDescendantsReq) ([]*model.DirEntry, error)) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = stub
}

func (fake *FakeNode) ListDescendantsArgsForCall(i int) (context.Context, chan model.Event, string, model.ListDescendantsReq) {
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	argsForCall := fake.listDescendantsArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeNode) ListDescendantsReturns(result1 []*model.DirEntry, result2 error) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = nil
	fake.listDescendantsReturns = struct {
		result1 []*model.DirEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) ListDescendantsReturnsOnCall(i int, result1 []*model.DirEntry, result2 error) {
	fake.listDescendantsMutex.Lock()
	defer fake.listDescendantsMutex.Unlock()
	fake.ListDescendantsStub = nil
	if fake.listDescendantsReturnsOnCall == nil {
		fake.listDescendantsReturnsOnCall = make(map[int]struct {
			result1 []*model.DirEntry
			result2 error
		})
	}
	fake.listDescendantsReturnsOnCall[i] = struct {
		result1 []*model.DirEntry
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) StartOp(arg1 context.Context, arg2 chan model.Event, arg3 model.StartOpReq) (map[string]*model.Value, error) {
	fake.startOpMutex.Lock()
	ret, specificReturn := fake.startOpReturnsOnCall[len(fake.startOpArgsForCall)]
	fake.startOpArgsForCall = append(fake.startOpArgsForCall, struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 model.StartOpReq
	}{arg1, arg2, arg3})
	fake.recordInvocation("StartOp", []interface{}{arg1, arg2, arg3})
	fake.startOpMutex.Unlock()
	if fake.StartOpStub != nil {
		return fake.StartOpStub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.startOpReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) StartOpCallCount() int {
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	return len(fake.startOpArgsForCall)
}

func (fake *FakeNode) StartOpCalls(stub func(context.Context, chan model.Event, model.StartOpReq) (map[string]*model.Value, error)) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = stub
}

func (fake *FakeNode) StartOpArgsForCall(i int) (context.Context, chan model.Event, model.StartOpReq) {
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	argsForCall := fake.startOpArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeNode) StartOpReturns(result1 map[string]*model.Value, result2 error) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = nil
	fake.startOpReturns = struct {
		result1 map[string]*model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) StartOpReturnsOnCall(i int, result1 map[string]*model.Value, result2 error) {
	fake.startOpMutex.Lock()
	defer fake.startOpMutex.Unlock()
	fake.StartOpStub = nil
	if fake.startOpReturnsOnCall == nil {
		fake.startOpReturnsOnCall = make(map[int]struct {
			result1 map[string]*model.Value
			result2 error
		})
	}
	fake.startOpReturnsOnCall[i] = struct {
		result1 map[string]*model.Value
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) TryResolve(arg1 context.Context, arg2 chan model.Event, arg3 string, arg4 string) (model.DataHandle, error) {
	fake.tryResolveMutex.Lock()
	ret, specificReturn := fake.tryResolveReturnsOnCall[len(fake.tryResolveArgsForCall)]
	fake.tryResolveArgsForCall = append(fake.tryResolveArgsForCall, struct {
		arg1 context.Context
		arg2 chan model.Event
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	fake.recordInvocation("TryResolve", []interface{}{arg1, arg2, arg3, arg4})
	fake.tryResolveMutex.Unlock()
	if fake.TryResolveStub != nil {
		return fake.TryResolveStub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.tryResolveReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeNode) TryResolveCallCount() int {
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	return len(fake.tryResolveArgsForCall)
}

func (fake *FakeNode) TryResolveCalls(stub func(context.Context, chan model.Event, string, string) (model.DataHandle, error)) {
	fake.tryResolveMutex.Lock()
	defer fake.tryResolveMutex.Unlock()
	fake.TryResolveStub = stub
}

func (fake *FakeNode) TryResolveArgsForCall(i int) (context.Context, chan model.Event, string, string) {
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	argsForCall := fake.tryResolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeNode) TryResolveReturns(result1 model.DataHandle, result2 error) {
	fake.tryResolveMutex.Lock()
	defer fake.tryResolveMutex.Unlock()
	fake.TryResolveStub = nil
	fake.tryResolveReturns = struct {
		result1 model.DataHandle
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) TryResolveReturnsOnCall(i int, result1 model.DataHandle, result2 error) {
	fake.tryResolveMutex.Lock()
	defer fake.tryResolveMutex.Unlock()
	fake.TryResolveStub = nil
	if fake.tryResolveReturnsOnCall == nil {
		fake.tryResolveReturnsOnCall = make(map[int]struct {
			result1 model.DataHandle
			result2 error
		})
	}
	fake.tryResolveReturnsOnCall[i] = struct {
		result1 model.DataHandle
		result2 error
	}{result1, result2}
}

func (fake *FakeNode) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getDataMutex.RLock()
	defer fake.getDataMutex.RUnlock()
	fake.labelMutex.RLock()
	defer fake.labelMutex.RUnlock()
	fake.listDescendantsMutex.RLock()
	defer fake.listDescendantsMutex.RUnlock()
	fake.startOpMutex.RLock()
	defer fake.startOpMutex.RUnlock()
	fake.tryResolveMutex.RLock()
	defer fake.tryResolveMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeNode) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ node.Node = new(FakeNode)
